name: check-labels
on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]
  pull_request_review:
    types: [submitted, dismissed]
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "passed"
