name: PR jobs
on:
  pull_request:
  merge_group:

jobs:
  prjob:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 90
      - name: PR status
        if: github.event_name == 'pull_request'
        run: "true"
      - name: Merge group status
        if: github.event_name == 'merge_group'
        run: "true"