name: New PR jobs
on:
  pull_request:

jobs:
  newprjob:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 60
      - name: test
        run: echo "Hello from pr job!"
      - name: fail
        run: "false"
