name: PR jobs
on:
  pull_request:

jobs:
  prjob:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 60
      - name: test
        run: echo "Hello from pr job!"
      - name: delay
        run: sleep 90
