name: PR jobs
on:
  pull_request:
  merge_group:

jobs:
  prjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ github.event }}
      - name: fail
        if: github.event == 'merge_group'
        run: "false"
      - name: fail2
        if: github.event == 'pull_request'
        run: "false"
      - name: fail anyways
        run: "false"
      - name: sleep
        run: sleep 60
