name: PR jobs
on:
  pull_request:
  merge_group:

jobs:
  prjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: "true"

  failing_pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        if: github.event_name == 'merge_group'
        run: "true"
      - name: fail2
        if: github.event_name == 'pull_request'
        run: "false"
      - name: failalways
        run: "true"
