name: PR jobs
on:
  pull_request:
  merge_group:

jobs:
  prjob:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 60
      - name: test
        run: echo ${{github.event}}
      - name: fail
        if: ${{github.event == "merge_group"
        run: "false"
