name: PR and MQ jobs
on:
  pull_request:
  merge_group:

jobs:
  bothjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello from pr & mq job!"
      - name: delay
        run: sleep 90
